version: 0.1

phases:
  install:
    commands:
      - npm install --prefix client
      - npm install --prefix customer
      - npm install

  build:
    commands:
      - npm run build --prefix client
      - npm run build --prefix customer
  post_build:
    commands:

artifacts:
  files:
    - "config/**/*"
    - "controller/**/*"
    - "middleware/**/*"
    - "migrations/**/*"
    - "models/**/*"
    - "routes/**/*"
    - "app.js"
    - "Procfile"
    - "package.json"
    - ".ebextensions/**/*"
    - ".npmrc"
    - "client/**/*"
    - "customer/**/*"
